"""empty message

Revision ID: 17ae1c5d0e
Revises: 27a566a47bfe
Create Date: 2014-09-08 09:30:45.211838

"""

# revision identifiers, used by Alembic.
revision = '17ae1c5d0e'
down_revision = '27a566a47bfe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foodtruck', 'block', type_=sa.String())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foodtruck', 'block')
    op.add_column('foodtruck', sa.Column('block', sa.INTEGER, autoincrement=False, nullable=True))
    ### end Alembic commands ###

