"""empty message

Revision ID: 27a566a47bfe
Revises: 50c76b63ed73
Create Date: 2014-09-08 09:28:32.594627

"""

# revision identifiers, used by Alembic.
revision = '27a566a47bfe'
down_revision = '50c76b63ed73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foodtruck', 'blocklot', type_=sa.String())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foodtruck', 'blocklot')
    op.add_column('foodtruck', sa.Column('blocklot', sa.INTEGER, autoincrement=False, nullable=True))
    ### end Alembic commands ###

