"""empty message

Revision ID: 2c93354bfb9c
Revises: None
Create Date: 2014-09-08 08:03:30.258500

"""

# revision identifiers, used by Alembic.
revision = '2c93354bfb9c'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2 as geo


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foodtruck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant', sa.String(), nullable=True),
    sa.Column('facility_type', sa.String(), nullable=True),
    sa.Column('cnn', sa.Integer(), nullable=True),
    sa.Column('locationDescription', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('blocklot', sa.Integer(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('lot', sa.String(), nullable=True),
    sa.Column('permit', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('food_items', sa.String(), nullable=True),
    sa.Column('x', sa.Numeric(), nullable=True),
    sa.Column('y', sa.Numeric(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('schedule_url', sa.Numeric(), nullable=True),
    sa.Column('noi_sent', sa.Numeric(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('prior_permit', sa.Boolean(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('location', geo.Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    (
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )
    op.drop_table('foodtruck')
    op.drop_table('users')
    ### end Alembic commands ###
