"""empty message

Revision ID: 3ed2e57dbb9c
Revises: 58c38bdd6305
Create Date: 2014-09-08 09:37:37.251700

"""

# revision identifiers, used by Alembic.
revision = '3ed2e57dbb9c'
down_revision = '58c38bdd6305'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodtruck', sa.Column('location_id', sa.Integer(), nullable=True))
    op.drop_column('foodtruck', 'locationid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodtruck', sa.Column('locationid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('foodtruck', 'location_id')
    ### end Alembic commands ###
