"""empty message

Revision ID: 4e4b3be35947
Revises: 17ae1c5d0e
Create Date: 2014-09-08 09:32:17.744465

"""

# revision identifiers, used by Alembic.
revision = '4e4b3be35947'
down_revision = '17ae1c5d0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodtruck', sa.Column('noi_sent_on', sa.Date(), nullable=True))
    op.drop_column('foodtruck', 'noi_sent')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodtruck', sa.Column('noi_sent', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('foodtruck', 'noi_sent_on')
    ### end Alembic commands ###
