"""empty message

Revision ID: 50c76b63ed73
Revises: ce77eeef3e1
Create Date: 2014-09-08 09:25:24.056380

"""

# revision identifiers, used by Alembic.
revision = '50c76b63ed73'
down_revision = 'ce77eeef3e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodtruck', sa.Column('location_description', sa.String(), nullable=True))
    op.drop_column('foodtruck', 'locationDescription')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodtruck', sa.Column('locationDescription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('foodtruck', 'location_description')
    ### end Alembic commands ###
