"""empty message

Revision ID: 58c38bdd6305
Revises: 4e4b3be35947
Create Date: 2014-09-08 09:36:02.570999

"""

# revision identifiers, used by Alembic.
revision = '58c38bdd6305'
down_revision = '4e4b3be35947'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodtruck', sa.Column('locationid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foodtruck', 'locationid')
    ### end Alembic commands ###
