"""empty message

Revision ID: ce77eeef3e1
Revises: 2c93354bfb9c
Create Date: 2014-09-08 08:52:29.315718

"""

# revision identifiers, used by Alembic.
revision = 'ce77eeef3e1'
down_revision = '2c93354bfb9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foodtruck', 'schedule_url', type_=sa.String())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foodtruck', 'schedule_url', type_=sa.Numeric())
    ### end Alembic commands ###
